name: test

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: [self-hosted, shared]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: echo ${{ github.event.pull_request.merge_commit_sha }}
